databricks_profile:
  target: dev
  outputs:
    dev:
      type: databricks
      host: https://adb-7405609302815556.16.azuredatabricks.net
      http_path: /sql/1.0/warehouses/<your-warehouse-id>
      token: **************
      catalog: adb_workspace_dev_7405609302815556
      schema: default
      threads: 4
